name: Build and Deploy backend
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASS}}
  DOCKER_REPO: nexus.caaat.pro/repository/docker-projects/company-api
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SERVER_PATH_APP: ${{ secrets.SERVER_PATH_APP }}

jobs:
  push-image-to-docker-hub:
    name: Build and Deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD nexus.caaat.pro

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        working-directory: ./
        run: |
          docker build . --file Dockerfile --tag $DOCKER_REPO:${{ steps.date.outputs.date }}
          docker build . --file Dockerfile --tag $DOCKER_REPO:latest

      - name: Docker Push
        run: |
          docker push $DOCKER_REPO:${{ steps.date.outputs.date }}
          docker push $DOCKER_REPO:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ SSH_HOST }}
          username: ${{ SSH_USER }}
          key: ${{ SSH_KEY }}
          port: ${{ SSH_PORT }}
          script: |
            cd ${{ SERVER_PATH_APP }}
            docker compose pull
            docker compose up -d --force-recreate
